"""update PostsTags table

Revision ID: 6ad99920b429
Revises: 9f3af8af659e
Create Date: 2024-07-13 19:15:18.344612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad99920b429'
down_revision: Union[str, None] = '9f3af8af659e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts_tags', sa.Column('post_id', sa.Uuid(), nullable=False))
    op.add_column('posts_tags', sa.Column('tag_id', sa.Uuid(), nullable=False))
    op.drop_constraint('posts_tags_posts_id_fkey', 'posts_tags', type_='foreignkey')
    op.drop_constraint('posts_tags_tags_id_fkey', 'posts_tags', type_='foreignkey')
    op.create_foreign_key(None, 'posts_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'posts_tags', 'posts', ['post_id'], ['id'])
    op.drop_column('posts_tags', 'tags_id')
    op.drop_column('posts_tags', 'posts_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts_tags', sa.Column('posts_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('posts_tags', sa.Column('tags_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts_tags', type_='foreignkey')
    op.drop_constraint(None, 'posts_tags', type_='foreignkey')
    op.create_foreign_key('posts_tags_tags_id_fkey', 'posts_tags', 'tags', ['tags_id'], ['id'])
    op.create_foreign_key('posts_tags_posts_id_fkey', 'posts_tags', 'posts', ['posts_id'], ['id'])
    op.drop_column('posts_tags', 'tag_id')
    op.drop_column('posts_tags', 'post_id')
    # ### end Alembic commands ###
